project:
  type: website

website:
  title: "frabot"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/B8ni
      - icon: twitter
        href: https://twitter.com/bot_fra
format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 1.22em

execute:
  freeze: auto




